os: Visual Studio 2017
version: "{branch}-{build}"

environment:
 PY_PYTHON: 2.7-32
 my_secret_a:
  secure: kPfHlAOr4ZcGv/XCSRBeainjAYGaqsTMU6+mMvgXOMg=
 my_secret_b:
  secure: neMaHS4sUE44BxKyxNgaTcCnK663C88hNtG75ALxzoE=

clone_depth: 1

init:
 - ps: Set-WinSystemLocale ja-JP
 - ps: Start-Sleep -s 10
 - ps: Restart-Computer
 - ps: Start-Sleep -s 10

install:
 - set PATH=%PATH%;C:\MinGW;C:\MinGW\bin;C:\MinGW\msys\1.0
 - git submodule update --init --recursive
 - nuget install secure-file -ExcludeVersion
 - secure-file\tools\secure-file -decrypt jptools\secret\knowlec-key171003.pfx.enc -secret %my_secret_a%
 - secure-file\tools\secure-file -decrypt jptools\secret\knowlec-key-pass.txt.enc  -secret %my_secret_b%

build_script:
 - set VERSION=2018.3jp
 - set UPDATEVERSIONTYPE=nvdajp
 - for /F "usebackq" %%t in (`jptools\nowdate.cmd`) do set NOWDATE=%%t
 - set VERSION=%VERSION%-beta
 - set VERSION=%VERSION%-%NOWDATE%
 - set UPDATEVERSIONTYPE=%UPDATEVERSIONTYPE%beta
 - echo %PUBLISHER% %UPDATEVERSIONTYPE% %VERSION%
 - ps: |
     $sconsArgs = "version_build=$env:APPVEYOR_BUILD_NUMBER"
     Set-AppveyorBuildVariable "sconsArgs" $sconsArgs
 - 'echo jptools\kcCertAllBuild.cmd %sconsArgs%'
 - jptools\kcCertAllBuild.cmd %sconsArgs%

artifacts:
 - path: output\*
