version: "{branch}-{build}"

branches:
 only:
  - jpbeta

environment:
 PY_PYTHON: 2.7-32

clone_depth: 1

install:
 - PATH %PATH%;C:\msys64\mingw64\bin;C:\msys64\usr\bin
 - git submodule update --init

build_script:
 - jptools\nonCertAllBuild.cmd

artifacts:
 - path: output\*
