os: Visual Studio 2017
version: "{branch}-{build}"

environment:
 PY_PYTHON: 2.7-32

clone_depth: 1

init:
 - ps: Set-WinSystemLocale ja-JP
 - ps: Start-Sleep -s 10
 - ps: Restart-Computer
 - ps: Start-Sleep -s 10

install:
 - set PATH=%PATH%;C:\MinGW;C:\MinGW\bin;C:\MinGW\msys\1.0
 - git submodule update --init --recursive

build_script:
 - set VERSION=2018.3jp
 - set UPDATEVERSIONTYPE=nvdajp
 - for /F "usebackq" %%t in (`jptools\nowdate.cmd`) do set NOWDATE=%%t
 - set VERSION=%VERSION%-beta
 - set VERSION=%VERSION%-%NOWDATE%
 - set VERSION=%VERSION%-noncert
 - set UPDATEVERSIONTYPE=%UPDATEVERSIONTYPE%beta
 - set PUBLISHER=nvdajp
 - echo %PUBLISHER% %UPDATEVERSIONTYPE% %VERSION%
 - ps: |
     $sconsArgs = "version_build=$env:APPVEYOR_BUILD_NUMBER"
     Set-AppveyorBuildVariable "sconsArgs" $sconsArgs
 - 'echo jptools\nonCertAllBuild.cmd %sconsArgs%'
 - jptools\nonCertAllBuild.cmd %sconsArgs%
 - jptools\tests.cmd

artifacts:
 - path: output\*
 - path: miscDepsJp\jptools\__h1output.txt
 - path: miscDepsJp\jptools\__h2output.txt
 - path: miscDepsJp\jptools\__test_log.txt
 - path: jptools\__jpdictest_log.txt
